language: python
python: 3.5
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pep8

install:
    - pip install tox

script:
    - tox
