name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JOB:
          - PYTHON: "3.7"
            TOXENV: "py37"
          - PYTHON: "3.8"
            TOXENV: "py38"
          - PYTHON: "3.9"
            TOXENV: "py39"
          - PYTHON: "3.10"
            TOXENV: "py310"
          - PYTHON: "3.11"
            TOXENV: "py311"
          - PYTHON: "pypy-3.9"
            TOXENV: "pypy3"
          - PYTHON: "pypy-3.10"
            TOXENV: "pypy3"

          - PYTHON: "3.11"
            TOXENV: "pep8"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        timeout-minutes: 3
        with:
          persist-credentials: false
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ matrix.JOB.PYTHON }}
      - run: pip install tox
      - run: tox -e "${{ matrix.JOB.TOXENV }}"
