name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JOB:
          - PYTHON: "3.8"
            TOXENV: "py38"
          - PYTHON: "3.9"
            TOXENV: "py39"
          - PYTHON: "3.10"
            TOXENV: "py310"
          - PYTHON: "3.11"
            TOXENV: "py311"
          - PYTHON: "3.12"
            TOXENV: "py312"
          - PYTHON: "pypy-3.9"
            TOXENV: "pypy3"
          - PYTHON: "pypy-3.10"
            TOXENV: "pypy3"

          - PYTHON: "3.12"
            TOXENV: "pep8"
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.JOB.PYTHON }}
      - run: pip install tox
      - run: tox -e "${{ matrix.JOB.TOXENV }}"
